#!/bin/bash

# The MIT License
# 
# Copyright (c) <2010> <Shaun T. Erickson>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

conf_dir=`dirname $0`
. ${conf_dir}/.smxyconf

if [ -n "${1}" ]
then
    cd ${bin}
    if [ "${1}" = "robust" -o "${1}" = "robust_hg" ]
    then
        mono-sgen Robust.exe -inifile=${etc}/${1}.ini -logconfig=${lc}/${1}.config
    else
        mkdir -p ${adb}/${1}
        MONO_ADDINS_REGISTRY=${adb}/${1} mono-sgen OpenSim.exe -inifile=${sd}/${1}.ini -logconfig=${lc}/${1}.config
    fi
else
    echo
    echo "Usage: `basename ${0}` {region_name}"
    echo
    exit 1
fi
