#!/bin/bash

# The MIT License
# 
# Copyright (c) <2010> <Shaun T. Erickson>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

conf_dir=`dirname $0`
. ${conf_dir}/.smxyconf

rev_region_names=""
for region in ${region_names}
do
    rev_region_names="${region} ${rev_region_names}"
done
rev_region_names=`echo ${rev_region_names} | sed -e 's/ $//'`

for region in ${rev_region_names}
do
    screen -X -S OpenSim -p ${region} stuff "shutdown
"
    if [ "${region}" = "robust" -o "${region}" = "robust_hg" ]
    then
        sleep 30
    else
        sleep ${wait_seconds}
    fi
done
